'''
Created on 7. des. 2014

@author: JohnArne
'''

TYPECRAFT_SENTIWORDNET = {  'ADJ':      'a',
                            'ADJC':     'a',
                            'ADJS':     'a',
                            'ADV':      'r',
                            'ADVm':     'r',
                            'ADVneg':   'r',
                            'ADVplc':   'r',
                            'ADVtemp':  'r',            
                            'CN':       'n',            
                            'N':        'n',            
                            'Nbare':    'n',            
                            'Ncomm':    'n',            
                            'NDV':      'n',            
                            'NFEM':     'n',            
                            'NMASC':    'n',            
                            'NNEUT':    'n',            
                            'NNO':      'n',            
                            'Np':       'n',            
                            'Nrel':     'n',            
                            'Nspat':    'n',            
                            'V':        'v',            
                            'V1':       'v',            
                            'V2':       'v',
                            'V3':       'v',
                            'V4':       'v',
                            'Vbid':     'v',
                            'Vcon':     'v',
                            'Vdtr':     'v',
                            'Vimprs':   'v',
                            'Vitr':     'v',
                            'VitrOBL':  'v',
                            'Vlght':    'v',
                            'Vmod':     'v',
                            'Vneg':     'v',
                            'Vpre':     'v',
                            'Vrefl':    'v',
                            'Vtr':      'v',
                            'VtrOBL':   'v',
                            'Vvec':     'v',
                            'Vvector':  'v'}
